<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.8.1">
]
>

<object class="java.util.Vector" name="__root__" version="3.8.1">
   <object class="weka.classifiers.bayes.NaiveBayes" name="0">
      <object array="yes" class="java.lang.String" name="options"/>
   </object>
   <object class="weka.classifiers.functions.SMO" name="1">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-C</object>
         <object class="java.lang.String" name="1">1.0</object>
         <object class="java.lang.String" name="2">-L</object>
         <object class="java.lang.String" name="3">0.001</object>
         <object class="java.lang.String" name="4">-P</object>
         <object class="java.lang.String" name="5">1.0E-12</object>
         <object class="java.lang.String" name="6">-N</object>
         <object class="java.lang.String" name="7">0</object>
         <object class="java.lang.String" name="8">-V</object>
         <object class="java.lang.String" name="9">-1</object>
         <object class="java.lang.String" name="10">-W</object>
         <object class="java.lang.String" name="11">1</object>
         <object class="java.lang.String" name="12">-K</object>
         <object class="java.lang.String" name="13">weka.classifiers.functions.supportVector.PolyKernel -E 1.0 -C 250007</object>
         <object class="java.lang.String" name="14">-calibrator</object>
         <object class="java.lang.String" name="15">weka.classifiers.functions.Logistic -R 1.0E-8 -M -1 -num-decimal-places 4</object>
      </object>
   </object>
   <object class="weka.classifiers.meta.AdaBoostM1" name="2">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-P</object>
         <object class="java.lang.String" name="1">100</object>
         <object class="java.lang.String" name="2">-S</object>
         <object class="java.lang.String" name="3">1</object>
         <object class="java.lang.String" name="4">-I</object>
         <object class="java.lang.String" name="5">10</object>
         <object class="java.lang.String" name="6">-W</object>
         <object class="java.lang.String" name="7">weka.classifiers.trees.DecisionStump</object>
      </object>
   </object>
   <object class="weka.classifiers.meta.LogitBoost" name="3">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-P</object>
         <object class="java.lang.String" name="1">100</object>
         <object class="java.lang.String" name="2">-L</object>
         <object class="java.lang.String" name="3">-1.7976931348623157E308</object>
         <object class="java.lang.String" name="4">-H</object>
         <object class="java.lang.String" name="5">1.0</object>
         <object class="java.lang.String" name="6">-Z</object>
         <object class="java.lang.String" name="7">3.0</object>
         <object class="java.lang.String" name="8">-O</object>
         <object class="java.lang.String" name="9">1</object>
         <object class="java.lang.String" name="10">-E</object>
         <object class="java.lang.String" name="11">1</object>
         <object class="java.lang.String" name="12">-S</object>
         <object class="java.lang.String" name="13">1</object>
         <object class="java.lang.String" name="14">-I</object>
         <object class="java.lang.String" name="15">10</object>
         <object class="java.lang.String" name="16">-W</object>
         <object class="java.lang.String" name="17">weka.classifiers.trees.DecisionStump</object>
      </object>
   </object>
   <object class="weka.classifiers.trees.DecisionStump" name="4">
      <object array="yes" class="java.lang.String" name="options"/>
   </object>
   <object class="weka.classifiers.trees.J48" name="5">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-C</object>
         <object class="java.lang.String" name="1">0.25</object>
         <object class="java.lang.String" name="2">-M</object>
         <object class="java.lang.String" name="3">2</object>
      </object>
   </object>
</object>
